### PR TITLE
Readme file edits

### PR DESCRIPTION
**Pull request by sittim**
Added some test to README

### CODE REVIEW

**Comment by szw** [comment]
Alright! I don't advise workspace autosaving, but... people seem to like it anyway, so :ok:. Thanks for contributing! :)

**Comment by sittim** [comment]
I looooooooooove workspace saving, it is crazy awesome.  I can hop on a plane, open up my laptop and be ready to roll as if I never turned the laptop off, in under 20 sec.  I use Dell Sputniks with Ubuntu base and i3wm, its a killer combination for on the go development...

**Comment by sittim** [comment]
Also, if I do a pull request, it does not mean that you have to use it, I will not be offended.  I am just trying to be helpful.

**Comment by szw** [comment]
Sure, I appreciate contributions :). But of course I wouldn't have merged it if I had found it pointless or contradictory to plugin philosophy. On the other hand more contributions provide more points of view and it's also valuable :).

**Pull request merged**
